// AI-generated with assistance
export const t = {
  appName: "Ventize",
  nav: {
    dashboard: "Dashboard",
    events: "Events",
    venues: "Venues",
    inbox: "Inbox",
    calendar: "Calendar",
    financials: "Financials",
  },
  dashboard: {
    events: "Events",
    customers: "Customers",
    bookings: "Bookings",
    revenue: "Revenue",
    upcomingSuffix: "upcoming",
    ticketSales: "Ticket Sales",
    salesRevenue: "Sales Revenue",
    popularEvents: "Popular Events",
    upcomingEvent: "Upcoming Event",
    inboxRatings: "Inbox & Ratings",
    recentBookings: "Recent Bookings",
    recentActivity: "Recent Activity",
    noUpcoming: "No upcoming events in the next 30 days.",
    viewDetails: "View details",
  },
  events: {
    title: "Events",
    new: "New Event",
    fields: {
      title: "Title",
      description: "Description",
      date: "Date & Time",
      location: "Location",
      maxSeats: "Max seats",
      price: "Price",
      venueId: "Venue ID (optional)",
    },
    create: "Create",
    loading: "Loading…",
    error: "Error",
  },
  venues: {
    title: "Venues",
    new: "New Venue",
    fields: {
      name: "Name",
      mapImage: "Map/Image (URL or file name)",
      address: "Address",
    },
    create: "Create",
    remove: "Remove",
  },
  eventDetails: {
    back: "Back",
    basePrice: "Base price",
    seats: "Seats",
    packages: "Packages",
    schedule: "Schedule",
    noPackages: "No packages defined.",
    noSchedule: "No schedule yet.",
    quickInfo: "Quick Info",
    venue: "Venue",
    ratings: "Ratings",
    leaveReview: "Leave a review",
    rating: "Rating (1–5)",
    comment: "Comment (optional)",
    send: "Send",
  },
};
